server:
  applicationConnectors:
    - type: http
      port: 9986
  adminConnectors:
    - type: http
      port: 9987
      
kafkaConsumer:
  topic: testTopic
  zookeeper: localhost:2181
  groupId: kafka_to_ws
